//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iris.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IrisDBEntities : DbContext
    {
        public IrisDBEntities()
            : base("name=IrisDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Δ_ΑΝΤΙΠΡΟΕΔΡΟΙ> Δ_ΑΝΤΙΠΡΟΕΔΡΟΙ { get; set; }
        public virtual DbSet<Δ_ΔΙΑΧΕΙΡΙΣΤΕΣ> Δ_ΔΙΑΧΕΙΡΙΣΤΕΣ { get; set; }
        public virtual DbSet<Δ_ΔΙΕΥΘΥΝΤΕΣ> Δ_ΔΙΕΥΘΥΝΤΕΣ { get; set; }
        public virtual DbSet<Δ_ΔΙΕΥΘΥΝΤΕΣ_ΓΕΝΙΚΟΙ> Δ_ΔΙΕΥΘΥΝΤΕΣ_ΓΕΝΙΚΟΙ { get; set; }
        public virtual DbSet<Δ_ΔΙΟΙΚΗΤΕΣ> Δ_ΔΙΟΙΚΗΤΕΣ { get; set; }
        public virtual DbSet<Δ_ΠΡΟΙΣΤΑΜΕΝΟΙ> Δ_ΠΡΟΙΣΤΑΜΕΝΟΙ { get; set; }
        public virtual DbSet<ΣΥΜΒΑΣΗ> ΣΥΜΒΑΣΗ { get; set; }
        public virtual DbSet<ΣΥΣ_ΕΓΓΡΑΦΟ_ΕΙΔΟΣ> ΣΥΣ_ΕΓΓΡΑΦΟ_ΕΙΔΟΣ { get; set; }
        public virtual DbSet<ΣΥΣ_ΕΚΠΑΙΔΕΥΤΙΚΕΣ_ΔΟΜΕΣ> ΣΥΣ_ΕΚΠΑΙΔΕΥΤΙΚΕΣ_ΔΟΜΕΣ { get; set; }
        public virtual DbSet<ΣΥΣ_ΠΑΡΑΜΕΤΡΟΙ_ΑΠΟΦΑΣΕΙΣ> ΣΥΣ_ΠΑΡΑΜΕΤΡΟΙ_ΑΠΟΦΑΣΕΙΣ { get; set; }
        public virtual DbSet<ΣΥΣ_ΠΕΡΙΦΕΡΕΙΑΚΕΣ> ΣΥΣ_ΠΕΡΙΦΕΡΕΙΑΚΕΣ { get; set; }
        public virtual DbSet<ΣΥΣ_ΠΡΟΚΗΡΥΞΗ_ΑΠΟΦΑΣΗ> ΣΥΣ_ΠΡΟΚΗΡΥΞΗ_ΑΠΟΦΑΣΗ { get; set; }
        public virtual DbSet<ΣΥΣ_ΣΧΟΛΙΚΑ_ΕΤΗ> ΣΥΣ_ΣΧΟΛΙΚΑ_ΕΤΗ { get; set; }
        public virtual DbSet<ΣΥΣ_ΦΥΛΑ> ΣΥΣ_ΦΥΛΑ { get; set; }
        public virtual DbSet<ΣΥΣ_ΩΡΟΜΙΣΘΙΑ> ΣΥΣ_ΩΡΟΜΙΣΘΙΑ { get; set; }
        public virtual DbSet<USER_ADMINS> USER_ADMINS { get; set; }
        public virtual DbSet<USER_SCHOOLS> USER_SCHOOLS { get; set; }
        public virtual DbSet<sqlUSER_SCHOOL> sqlUSER_SCHOOL { get; set; }
        public virtual DbSet<SYS_DIMOS> SYS_DIMOS { get; set; }
        public virtual DbSet<SYS_PERIFERIES> SYS_PERIFERIES { get; set; }
        public virtual DbSet<ΣΥΣ_ΣΧΟΛΕΣ> ΣΥΣ_ΣΧΟΛΕΣ { get; set; }
        public virtual DbSet<ΣΥΣ_ΚΛΑΔΟΙ> ΣΥΣ_ΚΛΑΔΟΙ { get; set; }
        public virtual DbSet<ΣΥΣ_ΕΠΙΤΡΟΠΕΣ_ΑΒ> ΣΥΣ_ΕΠΙΤΡΟΠΕΣ_ΑΒ { get; set; }
        public virtual DbSet<ΑΝΑΘΕΣΕΙΣ_ΑΚΥΡΩΤΙΚΕΣ> ΑΝΑΘΕΣΕΙΣ_ΑΚΥΡΩΤΙΚΕΣ { get; set; }
        public virtual DbSet<ΑΝΑΘΕΣΕΙΣ_ΑΚΥΡΩΤΙΚΕΣ_ΑΝ> ΑΝΑΘΕΣΕΙΣ_ΑΚΥΡΩΤΙΚΕΣ_ΑΝ { get; set; }
        public virtual DbSet<ΑΝΑΘΕΣΕΙΣ_ΑΝΑΚΛΗΣΗΣ> ΑΝΑΘΕΣΕΙΣ_ΑΝΑΚΛΗΣΗΣ { get; set; }
        public virtual DbSet<ΑΝΑΘΕΣΕΙΣ_ΑΝΑΚΛΗΣΗΣ_ΑΝ> ΑΝΑΘΕΣΕΙΣ_ΑΝΑΚΛΗΣΗΣ_ΑΝ { get; set; }
        public virtual DbSet<ΑΝΑΘΕΣΕΙΣ_ΑΠΕΥΘΕΙΑΣ> ΑΝΑΘΕΣΕΙΣ_ΑΠΕΥΘΕΙΑΣ { get; set; }
        public virtual DbSet<ΑΝΑΘΕΣΕΙΣ_ΑΡΧΙΚΕΣ> ΑΝΑΘΕΣΕΙΣ_ΑΡΧΙΚΕΣ { get; set; }
        public virtual DbSet<ΑΝΑΘΕΣΕΙΣ_ΑΡΧΙΚΕΣ_ΑΝ> ΑΝΑΘΕΣΕΙΣ_ΑΡΧΙΚΕΣ_ΑΝ { get; set; }
        public virtual DbSet<ΑΝΑΘΕΣΕΙΣ_ΣΥΜΠΛΗΡΩΜΑΤΙΚΕΣ> ΑΝΑΘΕΣΕΙΣ_ΣΥΜΠΛΗΡΩΜΑΤΙΚΕΣ { get; set; }
        public virtual DbSet<ΑΝΑΘΕΣΕΙΣ_ΣΥΜΠΛΗΡΩΜΑΤΙΚΕΣ_ΑΚ> ΑΝΑΘΕΣΕΙΣ_ΣΥΜΠΛΗΡΩΜΑΤΙΚΕΣ_ΑΚ { get; set; }
        public virtual DbSet<ΑΝΑΘΕΣΕΙΣ_ΣΥΜΠΛΗΡΩΜΑΤΙΚΕΣ_ΑΝ> ΑΝΑΘΕΣΕΙΣ_ΣΥΜΠΛΗΡΩΜΑΤΙΚΕΣ_ΑΝ { get; set; }
        public virtual DbSet<ΑΝΑΘΕΣΕΙΣ_ΤΡΟΠΟΠΟΙΗΤΙΚΕΣ> ΑΝΑΘΕΣΕΙΣ_ΤΡΟΠΟΠΟΙΗΤΙΚΕΣ { get; set; }
        public virtual DbSet<ΑΝΑΘΕΣΕΙΣ_ΤΡΟΠΟΠΟΙΗΤΙΚΕΣ_ΑΚ> ΑΝΑΘΕΣΕΙΣ_ΤΡΟΠΟΠΟΙΗΤΙΚΕΣ_ΑΚ { get; set; }
        public virtual DbSet<ΑΠΟΦΑΣΕΙΣ_ΑΚΥΡΩΤΙΚΕΣ> ΑΠΟΦΑΣΕΙΣ_ΑΚΥΡΩΤΙΚΕΣ { get; set; }
        public virtual DbSet<ΑΠΟΦΑΣΕΙΣ_ΑΚΥΡΩΤΙΚΕΣ_ΑΝ> ΑΠΟΦΑΣΕΙΣ_ΑΚΥΡΩΤΙΚΕΣ_ΑΝ { get; set; }
        public virtual DbSet<ΑΠΟΦΑΣΕΙΣ_ΑΝΑΚΛΗΣΗΣ> ΑΠΟΦΑΣΕΙΣ_ΑΝΑΚΛΗΣΗΣ { get; set; }
        public virtual DbSet<ΑΠΟΦΑΣΕΙΣ_ΑΝΑΚΛΗΣΗΣ_ΑΝ> ΑΠΟΦΑΣΕΙΣ_ΑΝΑΚΛΗΣΗΣ_ΑΝ { get; set; }
        public virtual DbSet<ΑΠΟΦΑΣΕΙΣ_ΑΠΕΥΘΕΙΑΣ> ΑΠΟΦΑΣΕΙΣ_ΑΠΕΥΘΕΙΑΣ { get; set; }
        public virtual DbSet<ΑΠΟΦΑΣΕΙΣ_ΔΙΟΡΘΩΤΙΚΕΣ> ΑΠΟΦΑΣΕΙΣ_ΔΙΟΡΘΩΤΙΚΕΣ { get; set; }
        public virtual DbSet<ΑΠΟΦΑΣΕΙΣ_ΔΙΟΡΘΩΤΙΚΕΣ_ΑΝ> ΑΠΟΦΑΣΕΙΣ_ΔΙΟΡΘΩΤΙΚΕΣ_ΑΝ { get; set; }
        public virtual DbSet<ΑΠΟΦΑΣΕΙΣ_ΣΥΜΠΛΗΡΩΜΑΤΙΚΕΣ> ΑΠΟΦΑΣΕΙΣ_ΣΥΜΠΛΗΡΩΜΑΤΙΚΕΣ { get; set; }
        public virtual DbSet<ΑΠΟΦΑΣΕΙΣ_ΣΥΜΠΛΗΡΩΜΑΤΙΚΕΣ_ΑΚ> ΑΠΟΦΑΣΕΙΣ_ΣΥΜΠΛΗΡΩΜΑΤΙΚΕΣ_ΑΚ { get; set; }
        public virtual DbSet<ΑΠΟΦΑΣΕΙΣ_ΣΥΜΠΛΗΡΩΜΑΤΙΚΕΣ_ΑΝ> ΑΠΟΦΑΣΕΙΣ_ΣΥΜΠΛΗΡΩΜΑΤΙΚΕΣ_ΑΝ { get; set; }
        public virtual DbSet<ΑΠΟΦΑΣΕΙΣ_ΤΡΟΠΟΠΟΙΗΤΙΚΕΣ> ΑΠΟΦΑΣΕΙΣ_ΤΡΟΠΟΠΟΙΗΤΙΚΕΣ { get; set; }
        public virtual DbSet<ΑΠΟΦΑΣΕΙΣ_ΤΡΟΠΟΠΟΙΗΤΙΚΕΣ_ΑΚ> ΑΠΟΦΑΣΕΙΣ_ΤΡΟΠΟΠΟΙΗΤΙΚΕΣ_ΑΚ { get; set; }
        public virtual DbSet<regΑΝΑΘΕΣΕΙΣ_ΠΡΟΣΛΗΨΗ> regΑΝΑΘΕΣΕΙΣ_ΠΡΟΣΛΗΨΗ { get; set; }
        public virtual DbSet<regΑΝΑΘΕΣΕΙΣ_ΠΡΟΣΛΗΨΗ_ΑΝ> regΑΝΑΘΕΣΕΙΣ_ΠΡΟΣΛΗΨΗ_ΑΝ { get; set; }
        public virtual DbSet<regΑΝΑΘΕΣΕΙΣ_ΜΕΤΑΒΟΛΗ> regΑΝΑΘΕΣΕΙΣ_ΜΕΤΑΒΟΛΗ { get; set; }
        public virtual DbSet<ΑΠΟΦΑΣΕΙΣ_ΑΡΧΙΚΕΣ> ΑΠΟΦΑΣΕΙΣ_ΑΡΧΙΚΕΣ { get; set; }
        public virtual DbSet<ΑΠΟΦΑΣΕΙΣ_ΑΡΧΙΚΕΣ_ΑΝ> ΑΠΟΦΑΣΕΙΣ_ΑΡΧΙΚΕΣ_ΑΝ { get; set; }
        public virtual DbSet<regΑΝΑΘΕΣΕΙΣ_ΜΕΤΑΒΟΛΗ_ΑΝ> regΑΝΑΘΕΣΕΙΣ_ΜΕΤΑΒΟΛΗ_ΑΝ { get; set; }
        public virtual DbSet<ΣΥΣ_ΕΝΤΥΠΑ> ΣΥΣ_ΕΝΤΥΠΑ { get; set; }
        public virtual DbSet<ΑΝΑΘΕΣΕΙΣ_ΚΑΘΟΛΙΚΟ> ΑΝΑΘΕΣΕΙΣ_ΚΑΘΟΛΙΚΟ { get; set; }
        public virtual DbSet<ΑΝΑΘΕΣΕΙΣ_ΤΡΟΠΟΠΟΙΗΤΙΚΕΣ_ΑΝ> ΑΝΑΘΕΣΕΙΣ_ΤΡΟΠΟΠΟΙΗΤΙΚΕΣ_ΑΝ { get; set; }
        public virtual DbSet<ΑΝΑΘΕΣΕΙΣ_ΤΡΟΠΟΠΟΙΗΤΙΚΕΣ_ΑΝ_ΑΚ> ΑΝΑΘΕΣΕΙΣ_ΤΡΟΠΟΠΟΙΗΤΙΚΕΣ_ΑΝ_ΑΚ { get; set; }
        public virtual DbSet<ΑΠΟΦΑΣΕΙΣ_ΤΡΟΠΟΠΟΙΗΤΙΚΕΣ_ΑΝ> ΑΠΟΦΑΣΕΙΣ_ΤΡΟΠΟΠΟΙΗΤΙΚΕΣ_ΑΝ { get; set; }
        public virtual DbSet<ΑΠΟΦΑΣΕΙΣ_ΤΡΟΠΟΠΟΙΗΤΙΚΕΣ_ΑΝ_ΑΚ> ΑΠΟΦΑΣΕΙΣ_ΤΡΟΠΟΠΟΙΗΤΙΚΕΣ_ΑΝ_ΑΚ { get; set; }
        public virtual DbSet<SYS_ANATHESI_TYPES> SYS_ANATHESI_TYPES { get; set; }
        public virtual DbSet<ΣΥΣ_ΕΙΔΙΚΟΤΗΤΕΣ_ΠΑΛΙΕΣ> ΣΥΣ_ΕΙΔΙΚΟΤΗΤΕΣ_ΠΑΛΙΕΣ { get; set; }
        public virtual DbSet<ΣΥΣ_ΚΛΑΔΟΙ_ΕΝΙΑΙΟΙ> ΣΥΣ_ΚΛΑΔΟΙ_ΕΝΙΑΙΟΙ { get; set; }
        public virtual DbSet<ΣΥΣ_ΕΙΔΙΚΟΤΗΤΕΣ> ΣΥΣ_ΕΙΔΙΚΟΤΗΤΕΣ { get; set; }
        public virtual DbSet<sqlEIDIKOTITES> sqlEIDIKOTITES { get; set; }
        public virtual DbSet<sqlEIDIKOTITES_OLDNEW> sqlEIDIKOTITES_OLDNEW { get; set; }
        public virtual DbSet<USER_ARIADNE> USER_ARIADNE { get; set; }
        public virtual DbSet<APP_STATUS> APP_STATUS { get; set; }
        public virtual DbSet<SYS_LOGINS> SYS_LOGINS { get; set; }
        public virtual DbSet<sqlSCHOOL_LOGINS> sqlSCHOOL_LOGINS { get; set; }
        public virtual DbSet<UPLOADS> UPLOADS { get; set; }
        public virtual DbSet<UPLOADS_FILES> UPLOADS_FILES { get; set; }
        public virtual DbSet<SYS_APOFASEIS_ALL> SYS_APOFASEIS_ALL { get; set; }
        public virtual DbSet<Δ2_ΑΝΤΙΠΡΟΕΔΡΟΙ> Δ2_ΑΝΤΙΠΡΟΕΔΡΟΙ { get; set; }
        public virtual DbSet<Δ2_ΔΙΑΧΕΙΡΙΣΤΕΣ> Δ2_ΔΙΑΧΕΙΡΙΣΤΕΣ { get; set; }
        public virtual DbSet<Δ2_ΔΙΕΥΘΥΝΤΕΣ> Δ2_ΔΙΕΥΘΥΝΤΕΣ { get; set; }
        public virtual DbSet<Δ2_ΔΙΕΥΘΥΝΤΕΣ_ΓΕΝΙΚΟΙ> Δ2_ΔΙΕΥΘΥΝΤΕΣ_ΓΕΝΙΚΟΙ { get; set; }
        public virtual DbSet<Δ2_ΔΙΟΙΚΗΤΕΣ> Δ2_ΔΙΟΙΚΗΤΕΣ { get; set; }
        public virtual DbSet<Δ2_ΠΡΟΙΣΤΑΜΕΝΟΙ> Δ2_ΠΡΟΙΣΤΑΜΕΝΟΙ { get; set; }
    }
}
