//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iris.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class regΑΝΑΘΕΣΕΙΣ_ΜΕΤΑΒΟΛΗ_ΑΝ
    {
        public int ID { get; set; }
        public string ΣΧΟΛ_ΕΤΟΣ { get; set; }
        public string ΕΠΩΝΥΜΙΑ { get; set; }
        public string ΜΟΝΑΔΑ { get; set; }
        public int ΑΝΑΘΕΣΗ_ΚΩΔ { get; set; }
        public string ΑΦΜ { get; set; }
        public string ΕΠΩΝΥΜΟ { get; set; }
        public string ΟΝΟΜΑ { get; set; }
        public string ΟΝΟΜΑΤΕΠΩΝΥΜΟ { get; set; }
        public string ΠΑΤΡΩΝΥΜΟ { get; set; }
        public Nullable<int> ΕΙΔΙΚΟΤΗΤΑ_ΚΩΔ { get; set; }
        public string ΕΙΔΙΚΟΤΗΤΑ { get; set; }
        public string ΚΛΑΔΟΣ { get; set; }
        public Nullable<short> ΩΡΕΣ_ΕΒΔ_ΑΠΟ { get; set; }
        public Nullable<short> ΩΡΕΣ_ΕΒΔ_ΣΕ { get; set; }
        public Nullable<int> ΣΧΟΛΗ { get; set; }
        public Nullable<int> ΣΧΟΛΙΚΟ_ΕΤΟΣ { get; set; }
        public string ΑΠΟΦΑΣΗ_ΕΙΔΟΣ { get; set; }
        public Nullable<int> ΑΠΟΦΑΣΗ_ΚΩΔ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΣΥΝΤΑΞΗ { get; set; }
        public Nullable<int> ΣΥΜΒΑΣΗ { get; set; }
        public string ΣΥΜΒΑΣΗ_ΕΙΔΟΣ { get; set; }
        public string ΕΠΩΝΥΜΙΑ_ΠΕΡΙΦΕΡΕΙΑ { get; set; }
        public string ΑΠΟΦΑΣΗ_ΠΡΩΤΟΚΟΛΛΟ { get; set; }
        public string ΔΙΑΧΕΙΡΙΣΤΗΣ { get; set; }
        public int ΚΩΔΙΚΟΣ_ΠΕΡΙΦΕΡΕΙΑ { get; set; }
        public Nullable<int> ΚΛΑΔΟΣ_ΚΩΔ { get; set; }
        public Nullable<int> ΩΡΟΜΙΣΘΙΟ_ΚΩΔ { get; set; }
        public Nullable<int> ΦΥΛΟ { get; set; }
        public string ΕΙΔΙΚΟΤΗΤΑ_ΕΝΙΑΙΑ { get; set; }
        public string ΠΕΡΙΦ_ΣΥΝΤΟΜΟΓΡΑΦΙΑ { get; set; }
    }
}
