//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iris.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sqlEIDIKOTITES_OLDNEW
    {
        public int ΚΩΔΙΚΟΣ { get; set; }
        public string ΕΙΔΙΚΟΤΗΤΑ_ΠΑΛΙΑ { get; set; }
        public string ΕΙΔΙΚΟΤΗΤΑ_ΝΕΑ { get; set; }
        public string ΚΛΑΔΟΣ_ΕΝΙΑΙΟΣ { get; set; }
        public Nullable<int> ΚΛΑΔΟΣ { get; set; }
    }
}
