//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iris.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_APOFASEIS_ALL
    {
        public int ROWID { get; set; }
        public int ΑΠΟΦΑΣΗ_ΚΩΔ { get; set; }
        public Nullable<int> ΣΧΟΛΙΚΟ_ΕΤΟΣ { get; set; }
        public Nullable<int> ΔΙΑΧΕΙΡΙΣΤΗΣ { get; set; }
        public Nullable<int> ΣΧΟΛΗ { get; set; }
        public Nullable<int> ΠΡΟΙΣΤΑΜΕΝΟΣ { get; set; }
        public Nullable<int> ΔΙΕΥΘΥΝΤΗΣ { get; set; }
        public Nullable<int> ΓΕΝΙΚΟΣ { get; set; }
        public Nullable<int> ΔΙΟΙΚΗΤΗΣ { get; set; }
        public Nullable<int> ΑΝΤΙΠΡΟΕΔΡΟΣ { get; set; }
        public string ΑΠΟΦΑΣΗ_ΕΙΔΟΣ { get; set; }
    }
}
