//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iris.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΑΠΟΦΑΣΕΙΣ_ΤΡΟΠΟΠΟΙΗΤΙΚΕΣ_ΑΚ
    {
        public int ΑΠΟΦΑΣΗ_ΚΩΔ { get; set; }
        public Nullable<int> ΣΧΟΛΙΚΟ_ΕΤΟΣ { get; set; }
        public Nullable<int> ΔΙΑΧΕΙΡΙΣΤΗΣ { get; set; }
        public Nullable<int> ΠΕΡΙΦΕΡΕΙΑΚΗ { get; set; }
        public Nullable<int> ΣΧΟΛΗ_ΤΥΠΟΣ { get; set; }
        public Nullable<int> ΣΧΟΛΗ { get; set; }
        public string ΑΡΧΙΚΗ_ΠΡΩΤΟΚΟΛΛΟ { get; set; }
        public string ΣΧΟΛΗ_ΕΓΓΡΑΦΟ { get; set; }
        public Nullable<System.DateTime> ΗΜΕΡΟΜΗΝΙΑ { get; set; }
        public string ΠΡΩΤΟΚΟΛΛΟ { get; set; }
        public string ΑΔΑ { get; set; }
        public Nullable<int> ΕΓΓΡΑΦΟ_ΕΙΔΟΣ { get; set; }
        public string ΚΕΙΜΕΝΟ_ΑΚ { get; set; }
        public Nullable<int> ΠΡΟΙΣΤΑΜΕΝΟΣ { get; set; }
        public Nullable<int> ΔΙΕΥΘΥΝΤΗΣ { get; set; }
        public Nullable<int> ΓΕΝΙΚΟΣ { get; set; }
        public Nullable<int> ΔΙΟΙΚΗΤΗΣ { get; set; }
        public Nullable<int> ΑΝΤΙΠΡΟΕΔΡΟΣ { get; set; }
        public bool ΥΠΟΓΡΑΦΩΝ { get; set; }
        public bool ΣΤΟ_ΟΡΘΟ { get; set; }
        public Nullable<System.DateTime> ΗΜΕΡΟΜΗΝΙΑ_ΟΡΘΟ { get; set; }
        public Nullable<System.DateTime> ΗΜΝΙΑ_ΣΥΝΤΑΞΗ { get; set; }
        public string ΑΠΟΦΑΣΗ_ΕΙΔΟΣ { get; set; }
        public string ΚΕΙΜΕΝΟ_ΥΠΟΨΗ { get; set; }
        public string ΑΠΟΦΑΣΗ_ΜΕΤΑΒΟΛΗΣ { get; set; }
    }
}
