//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iris.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΣΥΣ_ΠΑΡΑΜΕΤΡΟΙ_ΑΠΟΦΑΣΕΙΣ
    {
        public int ID { get; set; }
        public Nullable<int> ΣΧΟΛΙΚΟ_ΕΤΟΣ { get; set; }
        public string ΑΠΟΦΑΣΗ_ΕΓΚΡΙΤΙΚΗ { get; set; }
        public string ΠΥΣ_ΑΡΘΡΟ { get; set; }
        public string ΑΠΟΦΑΣΗ_ΥΠΟΥΡΓΟΣ { get; set; }
        public string ΑΠΟΦΑΣΗ_ΔΙΟΙΚΗΤΗΣ { get; set; }
        public string ΛΕΚΤΙΚΟ_ΥΠΟΥΡΓΟΥ { get; set; }
    }
}
