//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iris.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΣΥΣ_ΣΧΟΛΕΣ
    {
        public int ΣΧΟΛΗ_ΚΩΔ { get; set; }
        public string ΕΠΩΝΥΜΙΑ { get; set; }
        public Nullable<int> ΔΟΜΗ { get; set; }
        public Nullable<int> ΠΕΡΙΦΕΡΕΙΑΚΗ { get; set; }
        public string ΤΑΧ_ΔΙΕΥΘΥΝΣΗ { get; set; }
        public string ΤΗΛΕΦΩΝΑ { get; set; }
        public string ΓΡΑΜΜΑΤΕΙΑ { get; set; }
        public string ΦΑΞ { get; set; }
        public string EMAIL { get; set; }
        public string ΔΙΕΥΘΥΝΤΗΣ { get; set; }
        public Nullable<int> ΔΙΕΥΘΥΝΤΗΣ_ΦΥΛΟ { get; set; }
        public string ΚΙΝΗΤΟ { get; set; }
        public string ΥΠΟΔΙΕΥΘΥΝΤΗΣ { get; set; }
        public Nullable<int> ΥΠΟΔΙΕΥΘΥΝΤΗΣ_ΦΥΛΟ { get; set; }
        public Nullable<int> ΠΕΡΙΦΕΡΕΙΑ { get; set; }
    
        public virtual ΣΥΣ_ΠΕΡΙΦΕΡΕΙΑΚΕΣ ΣΥΣ_ΠΕΡΙΦΕΡΕΙΑΚΕΣ { get; set; }
        public virtual SYS_PERIFERIES SYS_PERIFERIES { get; set; }
    }
}
