//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iris.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΣΥΣ_ΠΡΟΚΗΡΥΞΗ_ΑΠΟΦΑΣΗ
    {
        public int ΚΩΔΙΚΟΣ { get; set; }
        public int ΣΧΟΛΙΚΟ_ΕΤΟΣ { get; set; }
        public string ΠΡΟΚΗΡΥΞΗ_ΑΠΟΦΑΣΗ_ΕΠΑΣ { get; set; }
        public string ΠΡΟΚΗΡΥΞΗ_ΑΠΟΦΑΣΗ_ΙΕΚ { get; set; }
        public string ΥΠΟΥΡΓΙΚΗ_ΑΠΟΦΑΣΗ_ΕΠΑΣ { get; set; }
        public string ΥΠΟΥΡΓΙΚΗ_ΑΠΟΦΑΣΗ_ΙΕΚ { get; set; }
        public string ΥΠΟΥΡΓΟΣ_ΛΕΚΤΙΚΟ { get; set; }
    }
}
