//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iris.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΣΥΣ_ΦΥΛΑ
    {
        public int ΦΥΛΟ_ΚΩΔ { get; set; }
        public string ΦΥΛΟ { get; set; }
    }
}
