//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iris.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΣΥΣ_ΕΙΔΙΚΟΤΗΤΕΣ
    {
        public int ΚΩΔΙΚΟΣ { get; set; }
        public string ΕΙΔΙΚΟΤΗΤΑ_ΚΩΔΙΚΟΣ { get; set; }
        public string ΕΙΔΙΚΟΤΗΤΑ_ΕΝΙΑΙΑ { get; set; }
        public string ΕΙΔΙΚΟΤΗΤΑ_ΛΕΚΤΙΚΟ { get; set; }
        public Nullable<int> ΚΛΑΔΟΣ_ΕΝΙΑΙΟΣ { get; set; }
        public Nullable<int> ΚΛΑΔΟΣ { get; set; }
        public string ΕΙΔΙΚΟΤΗΤΑ_ΕΝΙΑΙΑ1 { get; set; }
        public Nullable<bool> ΕΝΙΑΙΑ_ΧΡΗΣΗ { get; set; }
    
        public virtual ΣΥΣ_ΚΛΑΔΟΙ ΣΥΣ_ΚΛΑΔΟΙ { get; set; }
        public virtual ΣΥΣ_ΚΛΑΔΟΙ_ΕΝΙΑΙΟΙ ΣΥΣ_ΚΛΑΔΟΙ_ΕΝΙΑΙΟΙ { get; set; }
    }
}
