//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iris.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ΣΥΣ_ΕΠΙΤΡΟΠΕΣ_ΑΒ
    {
        public int ΕΠΙΤΡΟΠΗ_ΚΩΔ { get; set; }
        public string ΠΡΩΤΟΒΑΘΜΙΑ { get; set; }
        public string ΔΕΥΤΕΡΟΒΑΘΜΙΑ { get; set; }
        public Nullable<int> ΣΧΟΛΙΚΟ_ΕΤΟΣ { get; set; }
        public Nullable<int> ΠΕΡΙΦΕΡΕΙΑΚΗ { get; set; }
    }
}
